---
title: "Data generation"
author: "Theresa Siepe"
date: "2026-09-28"
output: html_document
---

This is a preliminary attempt to generate easy simulation scenarios on imbalanced groups and their predictions. 

# Set Up 

```{r}
# load libraries 
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
library(tidyverse)
library(patchwork)
library(marginaleffects)
library(randomForest)
library(MASS)
library(matlib)

library(renv) # reproducible environment package 
renv::init()
```

# Set up a function to generate the training data

```{r}

training_dg <- function(N = 50, group_distribution = 0.5, ev1 =0.25, ev2=0.25, seed = 223){
  
  # This functions generates training data with a 
  # given group distribution and event fraction
  # 
  # N <- total sample size (both groups combined)
  # group distribution <-   determines whether the groups are 
  #                         equally distributed = 0.5 or imbalanced != 0.5
  # ev1 <- event fraction for group 1
  # ev2 <- event fraction for group 2
  #
  set.seed(seed)
  
  gr1 <- round(N * group_distribution)
  gr2 <- N - gr1
  
  ####### Continuous predictor ######
  pred1 <- rnorm(N, mean = 0, sd = 1)
  
  ############# empty df ############
  training_dg <- data.frame(ID = seq(1, N),
                              Group = c(rep(1, gr1), rep(2, gr2)),
                              Predictor = pred1,
                              Event = c(rbinom(n = gr1, 1, prob = ev1),
                                        rbinom(n = gr2, 1, prob = ev2)))
  return(training_dg)
}


```
```{r}

```

