---
title: "Prediction Simulation"
author: "Theresa Siepe"
date: "2026-09-28"
output: html_document
---

```{r}
training_dg <- function(N = 50, group_distribution = 0.5, ev1 =0.25, ev2=0.25, seed = 223){
  
  # This functions generates training data with a 
  # given group distribution and event fraction
  # 
  # N <- total sample size (both groups combined)
  # group distribution <-   determines whether the groups are 
  #                         equally distributed = 0.5 or imbalanced != 0.5
  # ev1 <- event fraction for group 1
  # ev2 <- event fraction for group 2
  #
  set.seed(seed)
  
  gr1 <- round(N * group_distribution)
  gr2 <- N - gr1
  
  ####### Continuous predictor ######
  pred1 <- rnorm(N, mean = 0, sd = 1)
  
  ############# empty df ############
  training_dg <- data.frame(ID = seq(1, N),
                              Group = c(rep(1, gr1), rep(2, gr2)),
                              Predictor = pred1,
                              Event = c(rbinom(n = gr1, 1, prob = ev1),
                                        rbinom(n = gr2, 1, prob = ev2)))
  return(training_dg)
}
balanced_dt <- training_dg()
```

# Logistic Regression 

```{r}
logreg <- glm(Event ~ Group + Predictor, family = binomial, data = balanced_dt)

summary(logreg)
```

## Visualization of the group distributions

```{r}
pred_logreg <- predict(logreg, type = "response")

group1 <- pred_logreg[balanced_dt$Group == 1]
group2 <- pred_logreg[balanced_dt$Group == 2]

pred_logreg <- as.data.frame(cbind(group1, group2))
```

# Random forest 

```{r}
rf <- randomForest(Event ~ Group + Predictor,  data = balanced_dt)

pred_rf <- predict(rf)

group1 <- pred_rf[balanced_dt$Group == 1]
group2 <- pred_rf[balanced_dt$Group == 2]

pred_rf <- as.data.frame(cbind(group1, group2))
```

## Visualize 

```{r}
# long data format for predictions

pred_logreg_long <- pred_logreg |>
  pivot_longer(cols = everything(),       
               names_to = "name",
               values_to = "prediction")

pred_rf_long <- pred_rf |>
  pivot_longer(cols = everything(),       
               names_to = "name",
               values_to = "prediction")

plot_logreg <- pred_logreg_long |> 
  mutate(myaxis = paste0(name)) |>
  ggplot(aes(x = myaxis, y = prediction, fill = name, alpha = 0.3)) +
    geom_violin(width = 1.4) +
    geom_boxplot(width = 0.1, color = "azure1", alpha = 0.2) +
    annotate(
      "text",
      x = 1.5,
      y = Inf,
      label = paste0(
        "Event fraction Group 0: 0.5",
        "\nEvent fraction Group 1: 0.5",
        "\nSize of Group 0: 25",
        "\nSize of Group 1: 25"
      ),
      vjust = 1.2,
      hjust = 0.5,
      size = 3.5
    ) +
    theme_minimal() +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 15)
    ) +
    ggtitle("Log reg") +
    xlab("")

plot_rf <- pred_rf_long |> 
  mutate(myaxis = paste0(name)) |>
  ggplot(aes(x = myaxis, y = prediction, fill = name, alpha = 0.3)) +
    geom_violin(width = 1.4) +
    geom_boxplot(width = 0.1, color = "azure1", alpha = 0.2) +
    annotate(
      "text",
      x = 1.5,
      y = Inf,
      label = paste0(
        "Event fraction Group 0: 0.5",
        "\nEvent fraction Group 1: 0.5",
        "\nSize of Group 0: 25",
        "\nSize of Group 1: 25"
      ),
      vjust = 1.2,
      hjust = 0.5,
      size = 3.5
    ) +
    theme_minimal() +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 15)
    ) +
    ggtitle("Random Forest") +
    xlab("")

plot_logreg_rf <- (plot_logreg + plot_rf) &
  coord_cartesian(ylim = c(0.0, 0.8))
(plot_logreg_rf)
```

